version: "3.8"

volumes:
  esdata01:
    driver: local

networks:
  elastic:
    driver: bridge

services:
  # Just Elasticsearch - no security, no SSL
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    container_name: es01
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=home-soc
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    mem_limit: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic