packetbeat.interfaces.device: any

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols:
- type: dhcp
  ports: [67, 68]
- type: dns
  ports: [53]
- type: http
  ports: [80, 8080, 8000, 5000, 8002]
- type: https
  ports: [443]
- type: icmp
- type: tls
  ports: [443, 993, 995, 5223, 8443, 8883, 9243]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ['https://localhost:9200']
  username: '${ELASTIC_USER}'
  password: '${ELASTIC_PASSWORD}'
  ssl.certificate_authorities: ['/usr/share/packetbeat/certs/ca/ca.crt']